# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmDagWzG5dZJK1QAfpBnu3n1NXS_QIOz
"""

!pip install pandas datasets

import pandas as pd
from datasets import load_dataset

# 1. Download the raw dataset from Hugging Face
raw_data = load_dataset("bitext/Bitext-customer-support-llm-chatbot-training-dataset")

# 2. Convert it into a Pandas DataFrame (think of this as a code-based Excel sheet)
df = pd.DataFrame(raw_data['train'])

# 3. Data Cleaning: Drop rows with missing data and remove duplicate queries
df.dropna(subset=['instruction', 'response'], inplace=True)
df.drop_duplicates(subset=['instruction'], inplace=True)

# 4. Feature Selection: Keep only the columns we actually need for the AI
df = df[['category', 'instruction', 'response']]

# 5. Rename columns so they align with our business logic
df.columns = ['ticket_category', 'customer_query', 'historical_resolution']

# Display the first 5 rows to verify the cleaning worked
print(df.head())

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer
import numpy as np

# 1. Load the Multilingual Embedding Model
# This specific model understands over 50 languages and aligns them in the same semantic space
print("Downloading the multilingual embedding model (this may take a minute)...")
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

# 2. Extract a sample of our cleaned resolutions
# We use 100 rows to quickly test the pipeline
sample_resolutions = df['historical_resolution'].head(100).tolist()

# 3. Convert the text into vectors
print("Generating embeddings for the resolutions...")
resolution_embeddings = model.encode(sample_resolutions)

# 4. Verify the output
print(f"\nSuccessfully created {len(resolution_embeddings)} vector embeddings.")
print(f"Each vector is an array of {len(resolution_embeddings[0])} numbers.")
print("Here are the first 5 numbers of the first vector:")
print(resolution_embeddings[0][:5])

from sentence_transformers import util

# 1. Simulate an incoming customer ticket in German
# Meaning: "How do I create a new account?"
customer_query = "Wie erstelle ich ein neues Konto?"
print(f"Incoming Customer Query (German): '{customer_query}'\n")

# 2. Embed the query using the exact same model
query_embedding = model.encode(customer_query)

# 3. Perform the Semantic Search
# This calculates the cosine similarity between the query vector and all 100 stored resolution vectors
# top_k=1 tells the system to only return the single best match
hits = util.semantic_search(query_embedding, resolution_embeddings, top_k=1)

# 4. Extract the results
best_match_index = hits[0][0]['corpus_id']
similarity_score = hits[0][0]['score']

# 5. Display the matching document from our original Pandas DataFrame
print(f"Similarity Score: {similarity_score:.2f} (1.0 is a perfect semantic match)\n")
print("--- Retrieved Internal Resolution Document (English) ---")
print(df['historical_resolution'].iloc[best_match_index])

!pip install huggingface_hub

from huggingface_hub import InferenceClient

# 1. Initialize the client with your token
# We are using a highly capable open-source instruction model
client = InferenceClient(
    model="HuggingFaceH4/zephyr-7b-beta",
    token="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"
)

# 2. Extract the retrieved English document from the previous step
retrieved_context = df['historical_resolution'].iloc[best_match_index]

# 3. Construct the Prompt
# This is the "Prompt Engineering" layer where we instruct the LLM on how to behave
prompt = f"""
You are a professional customer support agent for a tech company.
A customer has asked the following query: "{customer_query}"

Using ONLY the information provided in the internal resolution document below, write a polite and helpful email response directly to the customer.
The response MUST be in the same language as the customer's query. Do not invent any new steps.

Internal Resolution Document:
{retrieved_context}

Final Response:
"""

# 4. Generate the Response
print("Generating final response via LLM...\n")
try:
    response = client.text_generation(
        prompt,
        max_new_tokens=250, # Limits the length of the response
        temperature=0.3,    # Keeps the response focused and factual rather than "creative"
    )
    print("--- Final Customer Email (German) ---")
    print(response.strip())
except Exception as e:
    print(f"Error during generation: {e}")

from huggingface_hub import InferenceClient

# 1. Initialize the client using the highly stable Llama-3 model
client = InferenceClient(
    model="meta-llama/Meta-Llama-3-8B-Instruct",
    token="os.environ.get("HF_TOKEN")"
)

# 2. Extract the retrieved English document from our database
retrieved_context = df['historical_resolution'].iloc[best_match_index]

# 3. Construct the Chat Messages
# Instead of a raw string, modern APIs use a structured list of messages
messages = [
    {
        "role": "system",
        "content": "You are a professional customer support agent. Use ONLY the provided Internal Document to answer the user. Respond in the exact same language as the user's query."
    },
    {
        "role": "user",
        "content": f"Customer Query: {customer_query}\n\nInternal Document: {retrieved_context}"
    }
]

# 4. Generate the Response using the modern Chat Completion API
print("Generating final response via LLM...\n")
try:
    response = client.chat.completions.create(
        messages=messages,
        max_tokens=250,
        temperature=0.3,
    )

    print("--- Final Customer Email (German) ---")
    # Extracting the text from the structured API response
    print(response.choices[0].message.content.strip())

except Exception as e:
    print(f"Error during generation: {e}")